spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sample_db_1?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,log4j
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    useGlobalDataSourceStat: true
#  druid:
#    max-wait: 30000
#    query-timeout: 10
#    validation-query: SELECT 1
#    use-global-data-source-stat: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100 #连接池最大连接数（负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
        max-idle: 200 #连接池最大空闭连接数
        min-idle: 50 #连接汉最小空闲连接数
    timeout: 600 #连接超时时间（毫秒）
mybatis:
  #  classpath:com/hgwxr/springweb2/springwebsample2/mapper/xml/*:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hgwxr.springweb2.springwebsample2.entity


